export type AuditConfig = {
  queueUrl: string;
  componentId: string;
};

const AUDIT_PREFIX = "IPV_HMRC_RECORD_CHECK_CRI";
export const AUDIT_EVENT_TYPE = {
  REQUEST_SENT: `${AUDIT_PREFIX}_REQUEST_SENT`,
  RESPONSE_RECEIVED: `${AUDIT_PREFIX}_RESPONSE_RECEIVED`,
  VC_ISSUED: `${AUDIT_PREFIX}_VC_ISSUED`,
  END: `${AUDIT_PREFIX}_END`,
  ABANDONED: `${AUDIT_PREFIX}_ABANDONED`,
} as const;
