name: check-vulnerabilities.yml

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions: {}

jobs:
  check-vulnerabilities:
    uses: govuk-one-login/github-actions/.github/workflows/check-vulnerabilities.yml@<MERGED_SHA>
    with:
      package-json-path: package.json
      github-actions-ref: <MERGED_SHA>
    secrets:
      npm-audit-app-key: ${{ secrets.NPM_AUDIT_APP_KEY }}
