name: Integration tests

on: workflow_dispatch
permissions: {}

jobs:
  deploy:
    name: Preview
    uses: ./.github/workflows/deploy-branch.yml
    permissions:
      id-token: write
      contents: read

  api-tests:
    name: API tests
    needs: deploy
    uses: ./.github/workflows/run-apigw-tests.yml
    permissions:
      id-token: write
      contents: read
    with:
      stack-name: ${{ needs.deploy.outputs.stack-name }}
      aws-region: ${{ needs.deploy.outputs.aws-region }}

  stepfunction-aws-tests:
    name: SFN AWS tests
    needs: deploy
    uses: ./.github/workflows/run-sfn-aws-tests.yml
    permissions:
      id-token: write
      contents: read
    with:
      stack-name: ${{ needs.deploy.outputs.stack-name }}
      aws-region: ${{ needs.deploy.outputs.aws-region }}

  stepfunction-mocked-tests:
    name: SFN Mocked tests
    uses: ./.github/workflows/run-sfn-mocked-tests.yml

  eventbridge-abandon-tests:
    name: EVN Abandon tests
    needs: deploy
    uses: ./.github/workflows/run-evn-abn-tests.yml
    permissions:
      id-token: write
      contents: read
    with:
      stack-name: ${{ needs.deploy.outputs.stack-name }}
      aws-region: ${{ needs.deploy.outputs.aws-region }}

  eventbridge-nino-check-tests:
    name: EVN Nino tests
    needs: deploy
    uses: ./.github/workflows/run-evn-nino-tests-lambda.yml
    permissions:
      id-token: write
      contents: read
    with:
      stack-name: ${{ needs.deploy.outputs.stack-name }}
      aws-region: ${{ needs.deploy.outputs.aws-region }}

  eventbridge-issue-credential-check-tests:
    name: EVN Issue Credential tests
    needs: deploy
    uses: ./.github/workflows/run-evn-cred-tests.yml
    permissions:
      id-token: write
      contents: read
    with:
      stack-name: ${{ needs.deploy.outputs.stack-name }}
      aws-region: ${{ needs.deploy.outputs.aws-region }}
